title: Flora Documentation
description: Documentation for Flora, the Unity foliage system.
theme: just-the-docs

url: https://magneticarcade.github.io/flora-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
